
const routesConfig = {
    home:"/",
    nike:"/nike",
    nikeNam:"/nike-nam",
    nikeNu:"/nike-nu",
    cart:'/cart',
    adidas:"/adidas",
    adidasNam:"/adidas-nam",
    adidasNu:"/adidas-nu",
    jordan:"/jordan",
    airJordan:"/air-jordan",
    yeezy:"/yeezy",
    otherBrands:"/other-brands",
    sale:"/sale",
    dayGiay:"/day-giay",
    spaGiay:"/spa-giay",
    lienHe:"/lien-he",
    product:"/product",
    productDetail:"/product/:id",
    login:'/dangnhap',
    signup:'/dangki',
    checkOut:'/check-out',
    profile:'/profile/:id',
    admin:'/admin',
}
export default routesConfig;